Base:
  mode: classification
  backend: mobilenet_v3_small
  fc_head: mobilenet_v3_large
  loss_reduction: mean
  pretrained: true
  weight_loss: false
  apply_vertical_flip: true
  non_common_samples_mult_factor: 10
  normalize_input: false
  normalization_values:
    w:
      mean: -0.018824034575662323
      std: 0.8792444830575991
    v:
      mean: 8.688572070049393
      std: 4.7870690570321965
  dataset: tfm
  base_size: 320
  batch_size: 50
  classification_data:
    w:
      - left:
          input: [ None, 0.2]
          output: 1
      - slight:
          input: [ 0.2, -0.2]
          output: 0
      - right:
          input: [ -0.2, None]
          output: -1
    v:
      - fast:
          input: [ None, 9]
          output: 10
      - moderate:
          input: [ 9, None]
          output: 5