MobileSmallRegression:
  mode: regression
  backend: mobilenet_v3_small
  fc_head: custom_head
  pretrained: true
  weight_loss: false
  base_size: 320
  batch_size: 50
  regression_data :
    - w
    - v
