MobileSmallRegression4_noPretrain:
  mode: regression
  backend: mobilenet_v3_small
  fc_head: pilotnet
  loss_reduction: mean
  pretrained: false
  weight_loss: false
  apply_vertical_flip: true
  non_common_samples_mult_factor: 34
  base_size: 320
  batch_size: 50
  max_epocs: 100
  regression_data :
    - w
    - v
