ResnetRegression4:
  mode: regression
  backend: resnet34
  fc_head: custom_head
  loss_reduction: mean
  pretrained: true
  weight_loss: false
  apply_vertical_flip: true
  non_common_samples_mult_factor: 4
  base_size: 320
  batch_size: 50
  regression_data :
    - w
    - v