WV_9_4_CLASSES:
  mode: classification
  backend: vgg16
  fc_head: custom_head
  pretrained: true
  weight_loss: true
  base_size: 160
  batch_size: 40
  classification_data:
    w:
      - radically_left:
          input: [ None, 2]
          output: 2
      - strongly_left:
          input: [ 2, 1]
          output: 1.5
      - moderately_left:
          input: [ 1, 0.5]
          output: 0.7
      - slightly_left:
          input: [ 0.5, 0.1]
          output: 0.3
      - slight:
          input: [ 0.1, -0.1]
          output: 0
      - slightly_right:
          input: [ -0.1, -0.5]
          output: -0.3
      - moderately_right:
          input: [ -0.5, -1]
          output: -0.7
      - strongly_right:
          input: [-1, -2]
          output: -1.5
      - radically_right:
          input: [-2, None]
          output: -2