Base:
  mode: regression
  backend: pilotnet
  fc_head: pilotnet
  loss_reduction: mean
  pretrained: true
  weight_loss: false
  apply_vertical_flip: true
  non_common_samples_mult_factor: 10
  normalize_input: false
  normalization_values:
    w:
      mean: 0.02114243236940299
      std: 1.576674726479323
    v:
      mean: 7.569154228855722
      std: 2.8949472999086323
  dataset: new
  base_size: 320
  batch_size: 50
  regression_data :
    - w
    - v