Base:
  mode: regression
  backend: pilotnet
  fc_head: pilotnet
  loss_reduction: mean
  pretrained: true
  weight_loss: false
  apply_vertical_flip: true
  non_common_samples_mult_factor: 2
  normalize_input: false
  normalization_values:
    w:
      mean: -0.025263235294117645
      std: 0.8462687738294171
    v:
      mean: 6.94344685242518
      std: 2.9136962708741003
  dataset: tfm
  base_size: 320
  batch_size: 50
  regression_data :
    - w
    - v