Base:
  mode: regression
  backend: pilotnet
  fc_head: pilotnet
  loss_reduction: sum
  pretrained: true
  weight_loss: false
  apply_vertical_flip: true
  non_common_samples_mult_factor: 10
  normalize_input: true
  normalization_values:
    w:
      mean: -0.0768297032795419
      std: 1.1331185982071246
    v:
      mean: 6.18136387298282
      std: 2.466514191627031
  dataset: tfm
  base_size: 240
  batch_size: 50
  regression_data :
    - w
    - v