Base:
  mode: regression
  backend: mobilenet_v3_small
  fc_head: mobilenet_v3_large
  loss_reduction: mean
  pretrained: true
  weight_loss: false
  apply_vertical_flip: true
  non_common_samples_mult_factor: 2
  normalize_input: false
  normalization_values:
    w:
      mean: -0.018824034575662323
      std: 0.8792444830575991
    v:
      mean: 8.688572070049393
      std: 4.7870690570321965
  dataset: tfm
  base_size: 320
  batch_size: 50
  regression_data :
    - w
    - v