WV_10_8_CLASSES:
  mode: classification
  backend: resnet34
  fc_head: custom_head
  pretrained: true
  weight_loss: true
  base_size: 418
  batch_size: 40
  classification_data:
    v:
      - v8:
          input: [ None, 14]
          output: 14
      - v7:
          input: [ 14, 12]
          output: 13
      - v6:
          input: [ 12, 10 ]
          output: 11
      - v5:
          input: [ 10, 8 ]
          output: 9
      - v4:
          input: [ 8, 6 ]
          output: 7
      - v3:
          input: [ 6, 4 ]
          output: 5
      - v2:
          input: [ 4, 2 ]
          output: 3
      - v1:
          input: [ 2, None ]
          output: 0